=== yiruhe/base/xml/bin/com/tz/xml/node.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.w3">
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="student">
                        <xs:complexType >
                                <xs:sequence>
                                    <xs:element name="name" type="xs:string"/>
                                    <xs:element name="gender" type="xs:string"/>
                                    <xs:element name="age" type="xs:int"/>
                                </xs:sequence>
                             <xs:attribute name="num" type="xs:ID" use="required"/>
                        </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yiruhe/base/xml/bin/com/tz/xml/nodeDemo.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<contacts xmlns="http://www.w3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3 node.xsd">
    <student num="a">
        <name>Hello</name>
        <gender>man</gender>
        <age>1</age>
    </student>
    <student num="b">
        <name>back</name>
        <gender>man</gender>
        <age>1</age>
    </student>
    <student num="c">
        <name>back</name>
        <gender>man</gender>
        <age>1</age>
    </student>
    <student num="e">
        <name>西门吹雪</name>
        <gender>man</gender>
        <age>20</age>
    </student>
</contacts>
